Module 1:  Contact form
boniface193/my-portfolio pull request #3
Opened 2022-12-06 16:45 UTC by boniface193

### Third milestone of my portfolio website

 - Created form with HTML5 validations.
 - collaborated with coding partner
 - [Formspree service](https://formspree.io/html). was added

2022-12-06 17:08 UTC, amejid requested changes
Hi @boniface193, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct use of Github flow :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 
- Good UI design :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 17:08 UTC, amejid commented on style.css
> +}
- [ ] Your design deserves a :+1:, kindly use flexbox to align the contents of your form as it is mentioned in the project requirement.

<img src="https://user-images.githubusercontent.com/17243325/205974932-161613f1-cc01-463c-af7f-b317148af5cd.png">

2022-12-06 17:08 UTC, amejid commented on index.html
> +                                <input type="email" required name="email" placeholder="your name" class="weight--400">
- [ ] I think this input is to receive the email of a user. Kindly use the correct placeholder text to give users an emphasis on what to put in that input. 😎️

2022-12-07 08:01 UTC, jerryowusu approved these changes
Hi @boniface193 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![good-fine](https://user-images.githubusercontent.com/65233860/206121518-a0d30d2d-ecd6-4452-a4e2-b5e9e66f7d3c.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Correct use of GitHub flow


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 08:11 UTC, merged