Module 1: Portfolio desktop version
boniface193/my-portfolio pull request #5
Opened 2022-12-08 21:29 UTC by boniface193

### Portfolio: desktop version

- I use media queries to make sure that my website displays correctly on desktop screens.
- linter was used to check syntax error

2022-12-08 22:08 UTC, rskinnerc requested changes
Hi @boniface193 👋👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![giphy](https://user-images.githubusercontent.com/26911718/206573647-feecc7f7-ab39-4281-9293-4d26588a9249.gif)


## Highlights
- Good job using grid and flexbox to layout the elements on the page
- Great usage of separate background images to resemble the template
- Linters are correctly configured and passing ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Adding the correct anchor destination to the nav links. For example, you could add an `id` of `contact` to the contact section, and then in the nav link the href should be `#contact`, that way, whenever a user clicks any link, it would take the user to the desired section of the page.
- Right now the logo in your README.md is not appearing and looks like it is missing. Please consider adding the missing image (your custom logo) or removing it completely


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 22:08 UTC, rskinnerc commented on style.css
> +@media (max-width: 768px) {
♻️ Well done! You implemented media queries for this task 😃😃😃. However, please note there are some issues you need to work on to make your project look like the template.

Currently, the design becomes responsive when the viewport hits 769px. A better approach could've to make everything by default mobile first (that is, outside of any media query) and then change styles only when the screen hits a certain width (as per the requirements, 768px). that way you don't have to worry about mobile styles because they are the default.

 - [x] Please make sure you set the media query `min-width` to 768px. That way, everything inside that block, will take effect when the screen is 768px or wider.

Right now, at 768px, it is still a mobile version.
![image](https://user-images.githubusercontent.com/26911718/206574676-43438950-045f-46f4-b461-37394e9ffc0d.png)

2022-12-08 22:08 UTC, rskinnerc commented on index.html
> +        <header>
♻️ Awesome, your design looks very similar to the template  😉😉. However, please note how at 769px, even though the header section became the desktop version, the with is not taking the full-screen width:

![image](https://user-images.githubusercontent.com/26911718/206575226-09ffefcc-1b01-42cc-b490-d12a6ace3935.png)


- [x] Kindly make sure that once the desktop version styles are applied, it takes the whole width of the screen.

2022-12-08 22:08 UTC, rskinnerc commented on index.html
>                              <li class="canopy-bold">CANOPY</li>
♻️ Good job implementing the mobile version of the projects section. however, please note how those project cards are being positioned outside of the viewport (to the left) and also not fitting the right margin of the page.

![image](https://user-images.githubusercontent.com/26911718/206575621-c25cf402-8699-4384-b110-3961bc484183.png)

- [x] Kindly make sure that the width of those cards one the become desktop version fit the actual width of the viewport.

2022-12-08 22:08 UTC, rskinnerc commented on index.html
> +        <footer class="pt-114">
♻️ I appreciate how similar the styles you applied are to the template!! However, please note that some pixels before the design becomes desktop version, the about section is overlapping the last project card:

![image](https://user-images.githubusercontent.com/26911718/206576136-10212a87-ebbc-4ede-9ff1-5e20d7787032.png)

At that size, it's very likely that tablet users encounter this problem.

- [ ] Please make sure that your mobile version does not get affected when applying styles to the desktop version. Please double-check the about section/projects section when getting close to the 768px breakpoint

2022-12-08 22:08 UTC, rskinnerc commented on index.html
> +                    <aside>
♻️ The desktop version of the about section looks really nice. There is still a thing you should take care of. Currently, when surpassing the required breakpoint (768px) this section is not changing as it should. It only becomes desktop friendly at 1131px

![image](https://user-images.githubusercontent.com/26911718/206576687-97fcd1c9-b1b0-4acc-878d-56a220d857c7.png)


- [ ] Please make sure the desktop styles are applied to all the sections on the page as per the provided template. Being consistent throughout the page would make it way more professional.

2022-12-09 15:57 UTC, boniface193 commented on index.html
> +                    <aside>
there is not enough space to spread about sections in a row at 768px breakpoint width,  that was the reason i left it at a columns

2022-12-09 16:09 UTC, Favourezeugwa reviewed
Hi @boniface193 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌❌❌

You have submitted a project, that has Linter (stylint) failing. Kindly fix the linter errors and re submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-09 18:33 UTC, PinkMoon25 approved these changes
Hi @boniface193, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
Good job using grid and flexbox to layout the elements on the page :heavy_check_mark: 
Great usage of separate background images to resemble the template :heavy_check_mark: 
Linters are correctly configured and passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 18:46 UTC, merged